### ISSUE TITLE
Factory problem

### ISSUE THREAD

**Issue by wahono77** [truongld/generator-angular-lazyload#1]
I try this tools, and I try to create factory using "yo angular-lazyload:service customer", 
but when it's running I got error : 

Uncaught TypeError: Cannot read property 'factory' of undefined

What's wrong in my step?

Thanks

**Comment by truongld** [comment]
thank you, i've fixed
https://github.com/truongld/generator-angular-lazyload/commit/f3755b4e6541e8de0989cde0c48abfb51ac9f41e
